/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

import * as React from 'react';

import { ISampleMessageData } from './sample-message.data';
import { ISampleMessageProps } from './sample-message.props.autogenerated';

export interface ISampleMessageViewProps extends ISampleMessageProps<ISampleMessageData> {

}

/**
 *
 * SampleMessage component
 * @extends {React.PureComponent<ISampleMessageProps<ISampleMessageData>>}
 */
class SampleMessage extends React.PureComponent<ISampleMessageProps<ISampleMessageData>> {
    public render(): JSX.Element | null {

        return this.props.renderView(this.props);
    }
}

export default SampleMessage;
