/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

import * as React from 'react';

import { ISampleButtonData } from './sample-button.data';
import { ISampleButtonProps } from './sample-button.props.autogenerated';

export interface ISampleButtonViewProps extends ISampleButtonProps<ISampleButtonData> {

}

/**
 *
 * SampleButton component
 * @extends {React.PureComponent<ISampleButtonProps<ISampleButtonData>>}
 */
class SampleButton extends React.PureComponent<ISampleButtonProps<ISampleButtonData>> {
    public render(): JSX.Element | null {

        return this.props.renderView(this.props);
    }
}

export default SampleButton;
