/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

import * as React from 'react';

import { IBackgroundImageContainerData } from './background-image-container.data';
import { IBackgroundImageContainerProps } from './background-image-container.props.autogenerated';

export interface IBackgroundImageContainerViewProps extends IBackgroundImageContainerProps<IBackgroundImageContainerData> {

}

/**
 *
 * BackgroundImageContainer component
 * @extends {React.PureComponent<IBackgroundImageContainerProps<IBackgroundImageContainerData>>}
 */
class BackgroundImageContainer extends React.PureComponent<IBackgroundImageContainerProps<IBackgroundImageContainerData>> {
    public render(): JSX.Element | null {

        return this.props.renderView(this.props);
    }
}

export default BackgroundImageContainer;
